spring.application.name=api
server.port=8000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/reports-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/reports-realm/protocol/openid-connect/certs

logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG